# Generated by Django 2.2.4 on 2021-03-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='some_string'),
            preserve_default=False,
        ),
    ]
